###########
# HELPERS #
###########
# DOCKER BUILD
#  sudo docker buildx build --platform linux/amd64,linux/arm64 /mnt/storage/dockerfiles/ubuntu-24.04-apache-php/ -t fsismo/ubuntu-24.04-apache-php:latest -t fsismo/ubuntu-24.04-apache-php:v0.1 --push
# RUN
#  docker run --hostname ubuntu-24.04-apache-php --name ubuntu-24.04-apache-php \
#   -v /var/docker/www:/var/www \
#   -p 80:80  \
#   -d \
#   fsismo/ubuntu-24.04-apache-php
# IT BASH
#  docker container exec -u 0 -it ubuntu-24.04-apache-php bash
# STOP and RESET
#  sudo docker container stop ubuntu-24.04-apache-php && sudo docker container rm ubuntu-24.04-apache-php


#########
# IMAGE #
#########
FROM ubuntu:24.04

########################
# ENVIROMENT VARIABLES #
########################
ENV TZ=America/Argentina/Buenos_Aires
ARG DEBIAN_FRONTEND=noninteractive


############
# PACKAGES #
############
RUN apt update
RUN apt install -y apache2 curl ghostscript libapache2-mod-php php php-bcmath php-curl php-imagick php-intl php-json php-mbstring php-mysql php-xml php-zip
RUN a2enmod rewrite

############
# MY STUFF #
############
COPY ./etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/000-default.conf
#COPY ./opt/utils/services.sh /opt/utils/services.sh
#RUN sed -i 's/upload_max_filesize = 2M/upload_max_filesize = 20M/' /etc/php/8.1/apache2/php.ini
#RUN chmod +x /opt/utils/services.sh

#########
# PORTS #
#########
EXPOSE 80

###########
# SERVICE #
###########
#CMD [ "/opt/utils/services.sh" ]
#CMD [ "/usr/sbin/apache2ctl -D FOREGROUND" ]
ENTRYPOINT ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
