# Ubuntu 22.04 PHP 8.1 Wordpress
version: '3.1'
services:
  wordpress:
    environment:
      - TZ=America/Argentina/Buenos_Aires
    image: fsismo/ubuntu-22.04-apache-php:latest
    hostname: ubuntu-22.04-apache-php
    ports:
      - 80:80
    restart: always
    volumes:
      - ./html:/var/www/html