###########
# HELPERS #
###########
# DOCKER BUILD
#  sudo docker buildx build --platform linux/amd64,linux/arm64 /mnt/storage/dockerfiles/mariadb-10.6-focal-auto-backups/ -t fsismo/mariadb-10.6-focal-auto-backups:latest -t fsismo/mariadb-10.6-focal-auto-backups:v0.3 --push
# RUN
#  docker run --hostname mariadb --name mariadb-10.6-focal-auto-backups \
#   -e MARIADB_ROOT_PASSWORD=Sup3rS3cr3t \
#   -v /opt/docker/apache-mariadb/mariadb/data:/var/lib/mysql \
#   -v /opt/docker/apache-mariadb/mariadb/dbbackups:/var/dbbackups  \
#   -p 3306:3306  \
#   -d \
#   mariadb-10.6-focal-auto-backups
# IT BASH
#  docker container exec -u 0 -it mariadb-10.6-focal-auto-backups bash
# STOP and RESET
#  docker container stop mariadb-10.6-focal-auto-backups && docker container rm mariadb-10.6-focal-auto-backups
# SAVE
#  docker image save -o /mnt/storage/dockerimages/wadmin/mariadb-10.6-focal-auto-backups-v1.0.1.tar mariadb-10.6-focal-auto-backups:v1.0.1


#########
# IMAGE #
#########
FROM  mariadb:10.6-focal

########################
# ENVIROMENT VARIABLES #
########################
ENV TZ=America/Argentina/Buenos_Aires
ARG DEBIAN_FRONTEND=noninteractive


############
# PACKAGES #
############
RUN apt-get update
RUN apt install cron

############
# MY STUFF #
############
COPY ./opt/dbbackup /opt/dbbackup
COPY ./opt/utils/services.sh /opt/utils/services.sh
COPY ./etc/cron.d/* /etc/cron.d/
RUN chmod +x /opt/dbbackup/*.sh
RUN chmod +x /opt/utils/services.sh
RUN sed -i "s/shopt -s nullglob/shopt -s nullglob\n\/opt\/utils\/services.sh/" /usr/local/bin/docker-entrypoint.sh


#########
# PORTS #
#########
EXPOSE 3306
#EXPOSE 139
#EXPOSE 445

###########
# SERVICE #
###########
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["mariadbd"]