###########
# HELPERS #
###########
# DOCKER BUILD
#  sudo docker buildx build --platform linux/amd64,linux/arm64 /mnt/storage/dockerfiles/ubuntu-24.04-postfix-smtp-relay/ -t fsismo/ubuntu-24.04-postfix-smtp-relay:latest -t fsismo/ubuntu-24.04-postfix-smtp-relay:v0.1.$(date +"%Y%m%d-%H%M") --push
# RUN
#  docker run --hostname ubuntu-24.04-postfix-smtp-relay --name ubuntu-24.04-postfix-smtp-relay \
#   -p 25:25  \
#   -d \
#   fsismo/ubuntu-24.04-postfix-smtp-relay
# IT BASH
#  docker container exec -u 0 -it ubuntu-24.04-postfix-smtp-relay bash
# STOP and DELETE
#  sudo docker container stop ubuntu-24.04-postfix-smtp-relay && sudo docker container rm ubuntu-24.04-postfix-smtp-relay


#########
# IMAGE #
#########
FROM ubuntu:24.04

########################
# ENVIROMENT VARIABLES #
########################
ENV TZ=America/Argentina/Buenos_Aires
ARG DEBIAN_FRONTEND=noninteractive
ARG SMTP_HOSTNAME
ARG SMTP_NETWORK
ARG SMTP_EMAIL
ARG SMTP_EMAIL_PASSWORD
ARG SMTP_DOMAIN
ARG SMTP_SRV
ARG SMTP_PORT


############
# PACKAGES #
############
RUN apt update
RUN echo "postfix postfix/main_mailer_type select Internet Site"      | debconf-set-selections
RUN echo "postfix postfix/mailname         string your.hostname3.com" | debconf-set-selections
RUN apt install -y postfix 

############
# MY STUFF #
############
COPY ./opt/utils/services.sh /opt/utils/services.sh
RUN chmod +x /opt/utils/services.sh


#########
# PORTS #
#########
EXPOSE 25

###########
# SERVICE #
###########

CMD ["/opt/utils/services.sh"]
